version: "3.6"
services:
    MSSql:
        image: mcr.microsoft.com/mssql/server:2022-latest
        container_name: mssql
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=YourStrong@Passw0rd
        ports:
            - "1433:1433"