# Generated by Django 5.2.2 on 2025-06-08 15:46

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=200)),
                ('Password', models.CharField(max_length=200)),
                ('Email', models.CharField(validators=[django.core.validators.EmailValidator()])),
            ],
        ),
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
                ('Description', models.CharField()),
                ('FlavorProfile', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Value', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('AccountId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.account')),
                ('WineId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.wine')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Text', models.CharField()),
                ('AccountId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.account')),
                ('WineId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.wine')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='LikedWines',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.wine'),
        ),
    ]
